dims_rename_dict = {}

# Specify the preferred units, and it will convert if the conversion is available in unit_conversion
preferred_units = ['m s-1', 'dbar', 'Celsius', 'psu', 'umol kg-1', 'gamma', 'm']

# String formats for units.  The key is the original, the value is the desired format
unit_str_format = {
    'cm_per_s': 'cm s-1',
    'meters': 'm',
    'deg c': 'Celcius',
    'psu': 'psu',
    'dyn. cm': 'cm',
    'gamma': 'gamma',
    'umol/kg': 'umol kg-1',
    'dbars': 'dbar',
}

# Various conversions from the key to units_name with the multiplicative conversion factor
unit_conversion = {
    'cm/s': {'units_name': 'm/s', 'factor': 0.01},
    'cm s-1': {'units_name': 'm s-1', 'factor': 0.01},
    'cm_per_s': {'units_name': 'm s-1', 'factor': 0.01},
    'meters': {'units_name': 'm', 'factor': 1},
    'cm': {'units_name': 'm', 'factor': 0.01},
    'dyn. cm': {'units_name': 'cm', 'factor': 1},
}

# Based on https://github.com/voto-ocean-knowledge/votoutils/blob/main/votoutils/utilities/vocabularies.py
standard_names = {
    "latitude": "LATITUDE",
    "longitude": "LONGITUDE",
    "z_depth": "DEPTH",
    "pr": "PRES",
    "ox": "DOXY",
    "te": "TEMP",
    "sa": "PSAL",
    "ctd_density": "POTDENS0", # Seawater potential density - need to check standard name for sigma
    "CAST": "CAST_NUMBER",
    "th": "THETA",
    "u_water_velocity_component": "U_WATER_VELOCITY",
    "v_water_velocity_component": "V_WATER_VELOCITY",
    "error_velocity": "ERROR_VELOCITY",
    "ga": "GAMMA",
    "ht": "DYN_HEIGHT",
    "gc_string": "GC_STRING",
}

vars_to_remove = []

vocab_attrs = {
    "LATITUDE": {
        "coordinate_reference_frame": "urn:ogc:crs:EPSG::4326",
        "long_name": "Latitude north",
        "observation_type": "measured",
        "platform": "platform",
        "reference": "WGS84",
        "standard_name": "latitude",
        "units": "degrees_north",
        "valid_max": 90,
        "valid_min": -90,
        "axis": "Y",
        "URI": "https://vocab.nerc.ac.uk/collection/OG1/current/LAT/",
    },
    "LONGITUDE": {
        "coordinate_reference_frame": "urn:ogc:crs:EPSG::4326",
        "long_name": "Longitude east",
        "observation_type": "measured",
        "platform": "platform",
        "reference": "WGS84",
        "standard_name": "longitude",
        "units": "degrees_east",
        "valid_max": 180,
        "valid_min": -180,
        "axis": "X",
        "URI": "https://vocab.nerc.ac.uk/collection/OG1/current/LON/",
    },
    "DATETIME": {
        "long_name": "time of measurement",
        "units": "UTC time",
        "observation_type": "measured",
        "standard_name": "time",
        "URI": "https://vocab.nerc.ac.uk/collection/P02/current/AYMD/",
    },
    "DEPTH": {
        "source": "pressure",
        "long_name": "glider depth",
        "standard_name": "depth",
        "units": "m",
        "comment": "from science pressure and interpolated",
        "sensor": "sensor_ctd",
        "observation_type": "calculated",
        "accuracy": 1,
        "precision": 2,
        "resolution": 0.02,
        "platform": "platform",
        "valid_min": 0,
        "valid_max": 2000,
        "reference_datum": "surface",
        "positive": "down",
    },
    "DOXY": {
        "long_name": "oxygen concentration",
        "observation_type": "calculated",
        "standard_name": "mole_concentration_of_dissolved_molecular_oxygen_in_sea_water",
        "units": "umol kg-1",
        "valid_max": 425,
        "valid_min": 0,
        "URI": "https://vocab.nerc.ac.uk/collection/P02/current/DOXY/",
    },
    "PRES": {
        "comment": "ctd pressure sensor",
        "sensor": "sensor_ctd",
        "long_name": "Pressure (spatial coordinate) exerted by the water body by profiling pressure sensor and "
        "correction to read zero at sea level",
        "observation_type": "measured",
        "positive": "down",
        "reference_datum": "sea-surface",
        "standard_name": "sea_water_pressure",
        "units": "dbar",
        "valid_max": 2000,
        "valid_min": 0,
        "URI": "https://vocab.nerc.ac.uk/collection/OG1/current/PRES",
    },
    "PSAL": {
        "long_name": "water salinity",
        "standard_name": "sea_water_practical_salinity",
        "units": "1e-3",
        "comment": "Practical salinity of the water body by CTD and computation using UNESCO 1983 algorithm",
        "sources": "CNDC, TEMP, PRES",
        "observation_type": "calculated",
        "sensor": "sensor_ctd",
        "valid_max": 40,
        "valid_min": 0,
        "URI": "https://vocab.nerc.ac.uk/collection/OG1/current/PSAL/",
    },
    "TEMP": {
        "long_name": "Temperature of the water body by CTD ",
        "observation_type": "measured",
        "standard_name": "sea_water_temperature",
        "units": "Celsius",
        "valid_max": 42,
        "valid_min": -5,
        "URI": "https://vocab.nerc.ac.uk/collection/OG1/current/TEMP/",
    },
    "THETA": {
        "long_name": "Potential temperature of the water body by computation using UNESCO 1983 algorithm.",
        "observation_type": "calculated",
        "sources": "salinity temperature pressure",
        "standard_name": "sea_water_potential_temperature",
        "units": "Celsius",
        "valid_max": 42,
        "valid_min": -5,
        "URI": "https://vocab.nerc.ac.uk/collection/OG1/current/THETA/",
    },
    "CAST_NUMBER": {
        "long_name": "Cast index",
        "units": "1",
    },
    "U_WATER_VELOCITY": {
        "long_name": "Eastward water velocity",
        "observation_type": "measured",
        "standard_name": "eastward_sea_water_velocity",
        "units": "m s-1",
        "valid_max": 3,
        "valid_min": -3,
        "URI": "",
    },
    "V_WATER_VELOCITY": {
        "long_name": "Northward water velocity",
        "observation_type": "measured",
        "standard_name": "northward_sea_water_velocity",
        "units": "m s-1",
        "valid_max": 3,
        "valid_min": -3,
        "URI": "",
    },
    "ERROR_VELOCITY": {
        "long_name": "Error in water velocity",
        "observation_type": "measured",
        "standard_name": "error_sea_water_velocity",
        "units": "m s-1",
        "valid_max": 2,
        "valid_min": 0,
        "URI": "",
    },
    "DYN_HEIGHT": {
        "long_name": "Dynamic height",
        "observation_type": "calculated",
        "standard_name": "sea_surface_height_above_geoid",
        "units": "m",
        "valid_max": 2,
        "valid_min": -2,
        "URI": "",
    },
    "GC_STRING": {
        "long_name": "GC string",
        "units": "1",
    },

}

# Various sensor vocabularies for OG1: http://vocab.nerc.ac.uk/scheme/OG_SENSORS/current/
sensor_vocabs = {
    "Seabird unpumped CTD": {
        "sensor_type": "CTD",
        "sensor_type_vocabulary": "https://vocab.nerc.ac.uk/collection/L05/current/130/",
        "sensor_maker": "Sea-Bird Scientific",
        "sensor_maker_vocabulary": "https://vocab.nerc.ac.uk/collection/L35/current/MAN0013/",
        "sensor_model": "Sea-Bird CT Sail CTD",
        "sensor_model_vocabulary": "http://vocab.nerc.ac.uk/collection/L22/current/TOOL1188/",
        "long_name": "Sea-Bird CT Sail CTD",
    },
    "RBR legato CTD": {
         "sensor_type": "CTD",
         "sensor_type_vocabulary": "https://vocab.nerc.ac.uk/collection/L05/current/130/",
         "sensor_maker": "RBR",
         "sensor_maker_vocabulary": "https://vocab.nerc.ac.uk/collection/L35/current/MAN0049/",
         "sensor_model": "RBR Legato3 CTD",
         "sensor_model_vocabulary": "https://vocab.nerc.ac.uk/collection/L22/current/TOOL1745/",
         "long_name": "RBR Legato3 CTD",
    },
    "Wetlabs BB2FL-VMT": {
        "sensor_type": "fluorometers",
        "sensor_type_vocabulary": "https://vocab.nerc.ac.uk/collection/L05/current/113/",
        "sensor_maker": "WET Labs",
        "sensor_maker_vocabulary": "https://vocab.nerc.ac.uk/collection/L35/current/MAN0026/",
        "sensor_model": "WET Labs {Sea-Bird WETLabs} ECO BB2FL-VMT backscattering fluorescence sensor",
        "sensor_model_vocabulary": "https://http://vocab.nerc.ac.uk/collection/L22/current/TOOL1310/",
        "long_name": "WET Labs ECO BB2FL-VMT",
    },
    "Wetlabs FLBBCD": {
        "sensor_type": "fluorometers",
        "sensor_type_vocabulary": "https://vocab.nerc.ac.uk/collection/L05/current/113/",
        "sensor_maker": "WET Labs",
        "sensor_maker_vocabulary": "https://vocab.nerc.ac.uk/collection/L35/current/MAN0026/",
        "sensor_model": "WET Labs {Sea-Bird WETLabs} ECO FLBBCD scattering fluorescence sensor",
        "sensor_model_vocabulary": "https://vocab.nerc.ac.uk/collection/L22/current/TOOL1141/",
        "long_name": "WET Labs ECO-FLBBCD",
    },
    "Wetlabs FLBBPC": {
        "sensor_type": "fluorometers",
        "sensor_type_vocabulary": "https://vocab.nerc.ac.uk/collection/L05/current/113/",
        "sensor_maker": "WET Labs",
        "sensor_maker_vocabulary": "https://vocab.nerc.ac.uk/collection/L35/current/MAN0026/",
        "sensor_model": "WET Labs {Sea-Bird WETLabs} ECO Puck Triplet FLBBPC scattering fluorescence sensor",
        "sensor_model_vocabulary": "https://vocab.nerc.ac.uk/collection/L22/current/TOOL1904/",
        "long_name": " WET Labs ECO FLBBPC",
    },
    "Wetlabs FLBBPE": {
        "sensor_type": "fluorometers",
        "sensor_type_vocabulary": "https://vocab.nerc.ac.uk/collection/L05/current/113/",
        "sensor_maker": "WET Labs",
        "sensor_maker_vocabulary": "https://vocab.nerc.ac.uk/collection/L35/current/MAN0026/",
        "sensor_model": "WET Labs {Sea-Bird WETLabs} ECO Triplet sensor",
        "sensor_model_vocabulary": "https://vocab.nerc.ac.uk/collection/L22/current/TOOL0674/",
        "long_name": "WET Labs ECO-FLBBCE",
    },
    "Wetlabs FLNTU": {
        "sensor_type": "fluorometers",
        "sensor_type_vocabulary": "https://vocab.nerc.ac.uk/collection/L05/current/113/",
        "sensor_maker": "WET Labs",
        "sensor_maker_vocabulary": "https://vocab.nerc.ac.uk/collection/L35/current/MAN0026/",
        "sensor_model": "WET Labs {Sea-Bird WETLabs} ECO FLNTU combined fluorometer and turbidity sensor",
        "sensor_model_vocabulary": "https://vocab.nerc.ac.uk/collection/L22/current/TOOL0215/",
        "long_name": " WET Labs ECO FLNTU",
    },
    "Nortek AD2CP": {
        "sensor_type": "ADVs and turbulence probes",
        "sensor_type_vocabulary": "https://vocab.nerc.ac.uk/collection/L05/current/384/",
        "sensor_maker": "Nortek",
        "sensor_maker_vocabulary": "https://vocab.nerc.ac.uk/collection/L35/current/MAN0068/",
        "sensor_model": "Nortek Glider1000 AD2CP Acoustic Doppler Current Profiler",
        "sensor_model_vocabulary": "https://vocab.nerc.ac.uk/collection/L22/current/TOOL1774/",
        "long_name": "Nortek AD2CP",
    },
    "JFE Advantech AROD_FT": {
        "sensor_type": "dissolved gas sensors",
        "sensor_type_vocabulary": "https://vocab.nerc.ac.uk/collection/L05/current/351/",
        "sensor_maker": "JFE Advantech",
        "sensor_maker_vocabulary": "https://vocab.nerc.ac.uk/collection/L35/current/MAN0053/",
        "sensor_model": "JFE Advantech Rinko FT ARO-FT oxygen sensor",
        "sensor_model_vocabulary": "https://vocab.nerc.ac.uk/collection/L22/current/TOOL1783/",
        "long_name": "JFE Rinko ARO-FT",
    },
    "RBR coda TODO": {
        "sensor_type": "dissolved gas sensors",
        "sensor_type_vocabulary": "https://vocab.nerc.ac.uk/collection/L05/current/351/",
        "sensor_maker": "RBR",
        "sensor_maker_vocabulary": "https://vocab.nerc.ac.uk/collection/L35/current/MAN0049/",
        "sensor_model": "RBR Coda T.ODO Temperature and Dissolved Oxygen Sensor",
        "sensor_model_vocabulary": "https://vocab.nerc.ac.uk/collection/L22/current/TOOL1783/",
        "long_name": "RBR Coda T.ODO",
    },
    "SeaBird OCR504": {
        "sensor_type": "radiometers",
        "sensor_type_vocabulary": "https://vocab.nerc.ac.uk/collection/L05/current/122/",
        "sensor_maker": "Sea-Bird Scientific",
        "sensor_maker_vocabulary": "https://vocab.nerc.ac.uk/collection/L35/current/MAN0013/",
        "sensor_model": "Satlantic {Sea-Bird} OCR-504 multispectral radiometer",
        "sensor_model_vocabulary": "https://vocab.nerc.ac.uk/collection/L22/current/TOOL0625/",
        "long_name": "Sea-Bird OCR-504 ",
    },
    "Seabird Deep SUNA": {
        "sensor_type": "nutrient analysers",
        "sensor_type_vocabulary": "https://vocab.nerc.ac.uk/collection/L05/current/181/",
        "sensor_maker": "Sea-Bird Scientific",
        "sensor_maker_vocabulary": "https://vocab.nerc.ac.uk/collection/L35/current/MAN0013/",
        "sensor_model": "Satlantic {Sea-Bird} Submersible Ultraviolet Nitrate Analyser V2 (SUNA V2) nutrient analyser series",
        "sensor_model_vocabulary": "https://vocab.nerc.ac.uk/collection/L22/current/TOOL1562/",
        "long_name": "Sea-Bird SUNA ",
    },
    "Franatech METS": {
        "sensor_type": "dissolved gas sensors",
        "sensor_type_vocabulary": "https://vocab.nerc.ac.uk/collection/L05/current/351/",
        "sensor_maker": "Franatech",
        "sensor_maker_vocabulary": "https://vocab.nerc.ac.uk/collection/L35/current/MAN0303/",
        "sensor_model": "Franatech METS Methane Sensor",
        "sensor_model_vocabulary": "https://vocab.nerc.ac.uk/collection/L22/current/TOOL1244/",
        "long_name": "Franatech METS Methane Sensor ",
    },
    "Biospherical MPE-PAR": {
        "sensor_type": "radiometers",
        "sensor_type_vocabulary": "https://vocab.nerc.ac.uk/collection/L05/current/122/",
        "sensor_maker": "Biospherical Instruments",
        "sensor_maker_vocabulary": "http://vocab.nerc.ac.uk/collection/L35/current/MAN0028/",
        "sensor_model": "Biospherical PAR sensor (UnSpec model)",
        "sensor_model_vocabulary": "https://vocab.nerc.ac.uk/collection/L22/current/TOOL1254/",
        "long_name": "Biospherical PAR sensor",
    },
    "Rockland Scientific MR1000G-RDL": {
        "sensor_type": "microstructure sensors",
        "sensor_type_vocabulary": "https://vocab.nerc.ac.uk/collection/L05/current/184/",
        "sensor_maker": "Rockland Scientific",
        "sensor_maker_vocabulary": "http://vocab.nerc.ac.uk/collection/L35/current/MAN0022/",
        "sensor_model": "Rockland MicroRider-1000",
        "sensor_model_vocabulary": "http://vocab.nerc.ac.uk/collection/L22/current/TOOL1232/",
        "long_name": "Rockland MicroRider-1000",
    },
    "Seabird SlocumCTD": {
        "sensor_type": "CTD",
        "sensor_type_vocabulary": "https://vocab.nerc.ac.uk/collection/L05/current/130/",
        "sensor_maker": "Sea-Bird Scientific",
        "sensor_maker_vocabulary": "http://vocab.nerc.ac.uk/collection/L35/current/MAN0013/",
        "sensor_model": "Sea-Bird Slocum Glider Payload {GPCTD} CTD",
        "sensor_model_vocabulary": "https://vocab.nerc.ac.uk/collection/L22/current/TOOL1492/",
        "long_name": "Sea-Bird Slocum CTD",
    },
    "SeaOWL UV-A": {
        "sensor_type": "fluorometers",
        "sensor_type_vocabulary": "https://vocab.nerc.ac.uk/collection/L05/current/113/",
        "sensor_maker": "WET Labs",
        "sensor_maker_vocabulary": "https://vocab.nerc.ac.uk/collection/L35/current/MAN0026/",
        "sensor_model": "WET Labs {Sea-Bird WETLabs} SeaOWL UV-A Sea Oil-in-Water Locator",
        "sensor_model_vocabulary": "https://vocab.nerc.ac.uk/collection/L22/current/TOOL1766/",
        "long_name": "WET Labs SeaOWL",
    },
    "Seabird SBE43F": {
        "sensor_type": "dissolved gas sensors",
        "sensor_type_vocabulary": "https://vocab.nerc.ac.uk/collection/L05/current/351/",
        "sensor_maker": "Sea-Bird Scientific",
        "sensor_maker_vocabulary": "http://vocab.nerc.ac.uk/collection/L35/current/MAN0013/",
        "sensor_model": "Sea-Bird SBE 43F Dissolved Oxygen Sensor",
        "sensor_model_vocabulary": "https://vocab.nerc.ac.uk/collection/L22/current/TOOL0037/",
        "long_name": "Sea-Bird SBE 43F",
    },
    "Gill Instruments GMX560": {
        "sensor_type": "meteorological packages",
        "sensor_type_vocabulary": "https://vocab.nerc.ac.uk/collection/L05/current/102/",
        "sensor_maker": "Gill Instruments",
        "sensor_maker_vocabulary": "https://vocab.nerc.ac.uk/collection/L35/current/MAN0121/",
        "sensor_model": "Gill Instruments MaxiMet Marine GMX560 weather station",
        "sensor_model_vocabulary": "http://vocab.nerc.ac.uk/collection/L22/current/TOOL2098/",
        "long_name": "Gill Instruments MaxiMet Marine GMX560 weather station",
    },
    "Datawell MOSE-G1000": {
        "sensor_type": "wave recorders",
        "sensor_type_vocabulary": "https://vocab.nerc.ac.uk/collection/L05/current/110/",
        "sensor_maker": "Datawell B.V.",
        "sensor_maker_vocabulary": "https://vocab.nerc.ac.uk/collection/L35/current/MAN0124/",
        "sensor_model": "Datawell MOSE-G1000",
        "sensor_model_vocabulary": "Datawell MOSE-G1000",
        "long_name": "Datawell MOSE-G1000",
    },
}